# Assignment

In [155]:
# Import 

import numpy as np
import matplotlib.pyplot as plt
from degree_freedom_queen import *
from degree_freedom_king1 import *
from degree_freedom_king2 import *
from generate_game import *
from Chess_env import *
from Policy import *

size_board = 4

## The Environment

You can find the environment in the file Chess_env, which contains the class Chess_env. To define an object, you need to provide the board size considered as input. In our example, size_board=4. 
Chess_env is composed by the following methods:

1. Initialise_game. The method initialises an episode by placing the three pieces considered (Agent's king and queen, enemy's king) in the chess board. The outputs of the method are described below in order.

     S $\;$ A matrix representing the board locations filled with 4 numbers: 0, no piece in that position; 1, location of the 
     agent's king; 2 location of the queen; 3 location of the enemy king.
     
     X $\;$ The features, that is the input to the neural network. See the assignment for more information regarding the            definition of the features adopted. To personalise this, go into the Features method of the class Chess_env() and change        accordingly.
     
     allowed_a $\;$ The allowed actions that the agent can make. The agent is moving a king, with a total number of 8                possible actions, and a queen, with a total number of $(board_{size}-1)\times 8$ actions. The total number of possible actions correspond      to the sum of the two, but not all actions are allowed in a given position (movements to locations outside the borders or      against chess rules). Thus, the variable allowed_a is a vector that is one (zero) for an action that the agent can (can't)      make. Be careful, apply the policy considered on the actions that are allowed only.
     

2. OneStep. The method performs a one step update of the system. Given as input the action selected by the agent, it updates the chess board by performing that action and the response of the enemy king (which is a random allowed action in the settings considered). The first three outputs are the same as for the Initialise_game method, but the variables are computed for the position reached after the update of the system. The fourth and fifth outputs are:

     R $\;$ The reward. To change this, look at the OneStep method of the class where the rewards are set.
     
     Done $\;$ A variable that is 1 if the episode has ended (checkmate or draw).
     
     
3. Features. Given the chessboard position, the method computes the features.

This information and a quick analysis of the class should be all you need to get going. The other functions that the class exploits are uncommented and constitute an example on how not to write a python code. You can take a look at them if you want, but it is not necessary.






In [156]:
## INITIALISE THE ENVIRONMENT

env=Chess_Env(size_board)

In [157]:
## PRINT 5 STEPS OF AN EPISODE CONSIDERING A RANDOM AGENT

S,X,allowed_a=env.Initialise_game()                       # INTIALISE GAME
print(env.Features())

print(S)                                                  # PRINT CHESS BOARD (SEE THE DESCRIPTION ABOVE)

print('check? ',env.check)                                # PRINT VARIABLE THAT TELLS IF ENEMY KING IS IN CHECK (1) OR NOT (0)
print('dofk2 ',np.sum(env.dfk2_constrain).astype(int))    # PRINT THE NUMBER OF LOCATIONS THAT THE ENEMY KING CAN MOVE TO


for i in range(5):
    
    a,_=np.where(allowed_a==1)                  # FIND WHAT THE ALLOWED ACTIONS ARE
    a_agent=np.random.permutation(a)[0]         # MAKE A RANDOM ACTION

    S,X,allowed_a,R,Done=env.OneStep(a_agent)   # UPDATE THE ENVIRONMENT
    
    
    ## PRINT CHESS BOARD AND VARIABLES
    print('')
    print(S)
    print(R,'', Done)
    print('check? ',env.check)
    print('dofk2 ',np.sum(env.dfk2_constrain).astype(int))
    
    
    # TERMINATE THE EPISODE IF Done=True (DRAW OR CHECKMATE)
    if Done:
        break

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[[0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 0]]
check?  0
dofk2  3

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 0 0]]
0  0
check?  0
dofk2  5

[[0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 

In [158]:
# INITIALISE THE PARAMETERS OF YOUR NEURAL NETWORK AND...
# PLEASE CONSIDER TO USE A MASK OF ONE FOR THE ACTION MADE AND ZERO OTHERWISE IF YOU ARE NOT USING VANILLA GRADIENT DESCENT...
# WE SUGGEST A NETWORK WITH ONE HIDDEN LAYER WITH SIZE 200.
from Q_values import Q_values
from SARSA import sarsa

S,X,allowed_a=env.Initialise_game()
N_a=np.shape(allowed_a)[0]   # TOTAL NUMBER OF POSSIBLE ACTIONS

N_in=np.shape(X)[0]    ## INPUT SIZE
N_h=200                ## NUMBER OF HIDDEN NODES



# HYPERPARAMETERS SUGGESTED (FOR A GRID SIZE OF 4)

epsilon_0 = 0.2     # STARTING VALUE OF EPSILON FOR THE EPSILON-GREEDY POLICY
# beta = 0.00005      # THE PARAMETER SETS HOW QUICKLY THE VALUE OF EPSILON IS DECAYING (SEE epsilon_f BELOW)
gamma = 0.85        # THE DISCOUNT FACTOR
# eta = 0.035        # THE LEARNING RATE

## INITALISE YOUR NEURAL NETWORK...
q_value = Q_values([N_in, N_h, N_a])
q_value.nn.momentum = 0.7
q_value.gamma = gamma

sarsa_v = sarsa([N_in, N_h, N_a])
sarsa_v.nn.momentum = 0.7
sarsa_v.gamma = gamma

N_episodes = 100000 # THE NUMBER OF GAMES TO BE PLAYED

def agent_action(value_function_model, X, allowed_a):
    (V,_) = value_function_model(X)
    allow_v = np.copy(V)
    allow_v[np.where(allowed_a.flatten()!=1)] = 0
    if (np.max(allow_v) == 0):
        return np.random.permutation(np.where(allowed_a.flatten()==1)[0])[0]
    else:
        return np.argmax(allow_v)

def play_one_game(value_function):
    S,X,allowed_a=env.Initialise_game()     # INITIALISE GAME
    Done=0                                  # SET Done=0 AT THE BEGINNING
    i=1                                     # COUNTER FOR THE NUMBER OF ACTIONS (MOVES) IN AN EPISODE
    while Done==0:
        a_agent = agent_action(value_function, X, allowed_a)
        S,X,allowed_a,R,Done=env.OneStep(a_agent)
        if Done:
            return (R,i)
        if i>16:
            return (R,i)
        i=i+1
def period_validate(function_model, validate_games):
    # SAVING VARIABLES
    R_save_temp = np.zeros([validate_games, 1])
    N_moves_save_temp = np.zeros([validate_games, 1])
    for n in range(validate_games):
        (R, n_moves) = play_one_game(function_model)
        R_save_temp[n]=np.copy(R)
        N_moves_save_temp[n]=np.copy(n_moves)
    return (np.mean(R_save_temp),np.mean(N_moves_save_temp))
def EMA(x, y):
    k = 2 / len(x)
    ema_seq=[]
    ema_prev=0
    for t in range(0, len(x)):
        y_t = y[t]*k + ema_prev *(1-k)
        ema_prev = y_t
        ema_seq.append(y_t)
    return (x, ema_seq)

In [159]:
def train(N_episodes, epsilon_0, model_value_function, model_training_function, model_calculate_next_R):
    # global sarsa_v
    # TRAINING LOOP BONE STRUCTURE
    R_period_seq = []
    N_period_step_seq = []
    x_period_axis = []

    R_training_seq = []
    N_training_seq = []
    x_training_seq = []

    beta = 0.00005      # THE PARAMETER SETS HOW QUICKLY THE VALUE OF EPSILON IS DECAYING (SEE epsilon_f BELOW)
    eta = 0.035

    for n in range(N_episodes):
        epsilon_f = epsilon_0 / (1 + beta * n)   ## DECAYING EPSILON
        sarsa_v.epsilon = epsilon_f

        Done=0                                   ## SET DONE TO ZERO (BEGINNING OF THE EPISODE)
        S,X,allowed_a=env.Initialise_game()

        while Done==0:                           ## START THE EPISODE
            ## THIS IS A RANDOM AGENT, CHANGE IT...
            (value_s, neuron_value) = model_value_function(X)
            a_agent=epsilon_greedy(value_s, np.asarray(allowed_a), epsilon_f)

            S_next,X_next,allowed_a_next,R,Done=env.OneStep(a_agent)

            if Done==1:
                model_training_function(eta, neuron_value, a_agent, R, value_s)
                break
            else:
                (V_next, _) = model_value_function(X_next)
                future_R = model_calculate_next_R(V_next, allowed_a_next)
                model_training_function(eta, neuron_value, a_agent, future_R, value_s,)

            # NEXT STATE AND CO. BECOME ACTUAL STATE...
            S=np.copy(S_next)
            X=np.copy(X_next)
            allowed_a=np.copy(allowed_a_next)

        ## record epic
        (R, n_moves) = play_one_game(model_value_function)
        x_training_seq.append(n)
        R_training_seq.append(R)
        N_training_seq.append(n_moves)
        # (_, ema_seq) = EMA(x_training_seq, R_training_seq)
        # if( len(ema_seq) > 1):
        #     ema_q = ema_seq[-1]
        #     if (ema_q>0.999):
        #         return [(x_period_axis, R_period_seq, N_period_step_seq),
        #                 (x_training_seq, R_training_seq, N_training_seq)]

        ## temp validate
        if (n % 1000 == 0 ):
            (avg_R, avg_n) = period_validate(model_value_function, 200)
            print(f"\r Training process {np.round(n/N_episodes*100,2)}%  "
                  f"avg_R: {np.round(avg_R,2)}, avg_steps:{np.round(avg_n,2)}", end="", flush=True)
            x_period_axis.append(n)
            R_period_seq.append(avg_R)
            N_period_step_seq.append(avg_n)
            if (avg_R > 0.99):
                return [(x_period_axis, R_period_seq, N_period_step_seq),
                        (x_training_seq, R_training_seq, N_training_seq)]
             # dead_neuron = 0
            # for (w,b) in q_value.nn.W_bias:
            #     for neuron_idx in range(w.shape[1]):
            #         if np.where(w[:, neuron_idx]==0)[0].shape[0] == w[:, neuron_idx].shape[0]:
            #             dead_neuron+=1

Q_traing_his = train(N_episodes, epsilon_0,
                                             lambda X: q_value.q_values(X),
                                             lambda eta, neuron_value, a_agent, R, qv_s: q_value.update_q_func(eta, neuron_value, a_agent, R, qv_s),
                                             lambda V_next, allowed_next: q_value.calculate_next_Q(V_next, allowed_a)
                                    )
(Q_x_axis, Q_R_seq, Q_N_step_seq) = Q_traing_his[0]
(Q_x_training_seq, Q_R_training_seq, Q_N_training_seq) = Q_traing_his[1]
print()
Sarsa_his = train(N_episodes, epsilon_0,
                                    lambda X: sarsa_v.sarsa_value(X),
                                    lambda eta, neuron_value, a_agent, R, qv_s: sarsa_v.update_sarsa_func(eta, neuron_value, a_agent, R, qv_s),
                                    lambda V_next, allowed_next: sarsa_v.calculate_next_V(V_next, allowed_a)
                                    )
(Sarsa_x_axis, Sarsa_R_seq, Sarsa_N_step_seq) = Sarsa_his[0]
(Sarsa_x_training_seq, Sarsa_R_training_seq, Sarsa_N_training_seq) = Sarsa_his[1]

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/lib/function_base.py:804: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, order=order, subok=subok, copy=True)


IndexError: index 8 is out of bounds for axis 0 with size 8

In [ ]:
# PERFORM N_episodes=1000 EPISODES MAKING RANDOM ACTIONS AND COMPUTE THE AVERAGE REWARD AND NUMBER OF MOVES
def test(agent, agent_tag):
    N_episodes=10000
    R_save = np.zeros([N_episodes, 1])
    N_moves_save = np.zeros([N_episodes, 1])
    for n in range(N_episodes):
        (R,i) = play_one_game(agent)
        R_save[n]=np.copy(R)
        N_moves_save[n]=np.copy(i)
    print(f'Agent {agent_tag}, Average reward:',np.mean(R_save),'Number of steps: ',np.mean(N_moves_save))
#random
# test(lambda X_in: (np.random.random(32), [] ), "Random Agent")
test(lambda X_in: q_value.q_values(X_in), "Q_agent")
test(lambda X_in: sarsa_v.sarsa_value(X_in), "Sarsa_agent")

In [ ]:
plt.figure(1)
plt.title("Average R value")
plt.plot(Q_x_axis, Q_R_seq, label="Q Learning")
plt.plot(Sarsa_x_axis, Sarsa_R_seq, label="SARSA")
plt.legend()

plt.figure(2)
plt.title("Average Checkmate steps")
plt.plot(Q_x_axis, Q_N_step_seq, label="Q learning")
plt.plot(Sarsa_x_axis, Sarsa_N_step_seq, label="SARSA")
plt.legend()


k = (len(Sarsa_x_training_seq))
(Sarsa_ema_x, Sarsa_R_ema) = EMA(Sarsa_x_training_seq, Sarsa_R_training_seq)
(Q_ema_x, Q_R_ema) = EMA(Q_x_training_seq, Q_R_training_seq)
(_, Sarsa_N_ema) = EMA(Sarsa_x_training_seq, Sarsa_N_training_seq)
(_, Q_N_ema) = EMA(Q_x_training_seq, Q_N_training_seq)
plt.figure(3)
plt.title("R EMA trend")
plt.plot(Q_ema_x, Q_R_ema, label="Q learning")
plt.plot(Sarsa_ema_x, Sarsa_R_ema, label="SARSA")
plt.legend()

plt.figure(4)
plt.title("N EMA trend")
plt.plot(Q_ema_x, Q_N_ema, label="Q learning")
plt.plot(Sarsa_ema_x, Sarsa_N_ema, label="SARSA")
plt.legend()